# This is a basic workflow to help you get started with Actions

name: dump ROM for OPPO PECM30

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      Rom_name:
        description: 'Rom_name'
        required: true
        default: './'
      token:
        description: "token"
        required: true
        default: ''
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Prepare environment
        run: |
          git clone https://github.com/Osilvfe/dumpyara.git
          cd dumpyara
          sudo bash ./setup.sh
          sudo apt install curl
          pip3 show pycryptodemo
          
          

     # - name: Download ROM files
     #   run: |
     #     bash ./download.sh
      
     # - name: Dump rom
     #   run: |
     #     bash ./dumpyara.sh ${{ github.event.inputs.Rom_name }} ${{ github.event.inputs.token }}
          
          
