# This is a basic workflow to help you get started with Actions

name: dump ROM for OPPO PECM30

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      Rom_URL:
        description: 'Rom_URL'
        required: true
        default: 'https://1400q5-my.sharepoint.com/personal/microadmin_1400q5_onmicrosoft_com/Documents/super.img'
      token:
        description: "token"
        required: true
        default: ''
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Prepare environment
        run: |
          git clone https://github.com/Osilvfe/dumpyara.git
          cd dumpyara
          sudo bash ./setup.sh
          sudo apt install curl
          
          

      - name: Download super.img
        run: |
          curl -o super.img ${{ github.event.inputs.Rom_URL }}

      - name: Dump rom
        run: |
          bash ./dumpyara "./super.img" ${{ github.event.inputs.token }}
          
          
