# This is a basic workflow to help you get started with Actions

name: dump ROM for OPPO PECM30

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      Rom_URL:
        description: 'Rom_URL'
        required: true
        default: 'https://1400q5-my.sharepoint.com/personal/microadmin_1400q5_onmicrosoft_com/Documents/super.img'
      token:
        description: "token"
        required: true
        default: ''
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Prepare environment
        run: |
          git clone https://github.com/Osilvfe/dumpyara.git
          cd dumpyara
          sudo bash ./setup.sh
          sudo apt install curl
          
          

      - name: Download super.img
        run: >
          curl 'https://1400q5-my.sharepoint.com/personal/microadmin_1400q5_onmicrosoft_com/_layouts/15/download.aspx?SourceUrl=%2Fpersonal%2Fmicroadmin%5F1400q5%5Fonmicrosoft%5Fcom%2FDocuments%2Fsuper%2Eimg' \
          -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
          -H 'accept-language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6' \
          -H 'cookie: MicrosoftApplicationsTelemetryDeviceId=a4708e08-b288-4006-8303-064c2ad1733d; MSFPC=GUID=f14b3522ba934c53a78fca94ba9f3beb&HASH=f14b&LV=202309&V=4&LU=1696031465562; SPOIDCRL=77u/PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48U1A+VjEzLDBoLmZ8bWVtYmVyc2hpcHwxMDAzMjAwMmQxODlmNWFkQGxpdmUuY29tLDAjLmZ8bWVtYmVyc2hpcHxtaWNyb2FkbWluQDE0MDBxNS5vbm1pY3Jvc29mdC5jb20sMTMzNjUyMjA5MzcwMDAwMDAwLDEzMzM2MTM4MDExMDAwMDAwMCwxMzM2NTY1Mjk1NTYzNDAwMDcsMTguMTgxLjE4My4xOTgsNDYxMTY4NjAxODQyNzM4Nzk3Myw1MjVkODcyMC00MTA3LTRmMTMtOTRhNS1jOGMzMGYwYTY1NTEsLDIwYjIwODY3LWY4NTktNGY1Ny05MjY1LTVkYWI0MDRmN2Y5MCw1YzZiM2JhMS02MDU0LTMwMDAtN2MwNy04OTUwNTg0NGRhZjIsNWM2YjNiYTEtNjA1NC0zMDAwLTdjMDctODk1MDU4NDRkYWYyLCwwLDAsMCwsLGV5SjFkR2tpT2lKT1lWTnljRkJpVldVd2FUUjFjbXh6YjNONVFrRkJJbjA9LDI2NTA0Njc3NDM5OTk5OTk5OTksMTMzNjUyMjA5MzcwMDAwMDAwLGRhMDdhZDBhLWVjYjAtNDUxNS05NTk2LTQ3YjI1NzRiYzVlMywsLCwsLDAsLDE5NTk5MSxEYURBZmpRUW1weU9YeDJScktfVzVsdm9MWjQsMEtOcWN4NzlHcEpIQzhWZGUvWTlaUlhMTkgyVXY2MlR4YlZJZU1qVmxxaGpWc1c2dTM3RHR3K2xZSnpEejNiOXJoMUhxZmJOZjVQajB5ZnN3TDNjTXA2RUZaVGRCdGwxc2Zlek1rdVRoK3FScXJSM2s0NWFpRW82QjN5NFI2T2h5T011cDBUczJuNGtzM215N29yQ1psckVYNElZSUR0Slo4YmtRNXY5TkNsaXVTeUZNa2NFOEVyWTd4L1Fad0Mzcjh2cC9HS1Y5QWxpWVo5OEtoQ1psczNldGtBOGU3ZDFhU0JLcmtGa25RK0ZySnNvaVE1ZnU3RHBudGt0cHV5MExwZHJRU1lqenZucm9wZ3NHT21rMVE1anNvMjFiRHlhbXlqbzVkbTV1dWlBTWEyM3JJQzZrUGl2N1lqa2hxR1l6WEl5YWk2bFF5ejkreFVpaEdVZXRnPT08L1NQPg==; FeatureOverrides_experiments=[]; ai_session=nd7zBcSnV0A5913W9n2FNu|1720785413559|1720785468465' \
          -H 'dnt: 1' \
          -H 'priority: u=0, i' \
          -H 'referer: https://1400q5-my.sharepoint.com/personal/microadmin_1400q5_onmicrosoft_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fmicroadmin%5F1400q5%5Fonmicrosoft%5Fcom%2FDocuments%2Fsuper%2Eimg&parent=%2Fpersonal%2Fmicroadmin%5F1400q5%5Fonmicrosoft%5Fcom%2FDocuments&ga=1' \
          -H 'sec-ch-ua: "Not/A)Brand";v="8", "Chromium";v="126", "Microsoft Edge";v="126"' \
          -H 'sec-ch-ua-mobile: ?0' \
          -H 'sec-ch-ua-platform: "Windows"' \
          -H 'sec-fetch-dest: iframe' \
          -H 'sec-fetch-mode: navigate' \
          -H 'sec-fetch-site: same-origin' \
          -H 'sec-fetch-user: ?1' \
          -H 'service-worker-navigation-preload: {"supportsFeatures":[]}' \
          -H 'upgrade-insecure-requests: 1' \
          -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0'
          --output super.img
      - name: Dump rom
        run: |
          bash ./dumpyara.sh "./super.img" ${{ github.event.inputs.token }}
          
          
